<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Amazon_Login_Excel</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>0578cb87-c196-4f61-8516-ad294e3dc325</testSuiteGuid>
   <testCaseLink>
      <guid>e12e923a-2309-4e48-b2b0-b37b248eaff4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Amazon/TC_Amazon_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>03a55059-6344-4eb9-b4cc-ec415ab991bc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Amazon_Login_Excel/Amazon_Excel_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>03a55059-6344-4eb9-b4cc-ec415ab991bc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>b4e188dc-5893-4a8f-9cd0-f58f874fb9d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>03a55059-6344-4eb9-b4cc-ec415ab991bc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>5ce4395d-a418-4c5e-9886-ea5c9742496e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
