<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit.add-to-cart</name>
   <tag></tag>
   <elementGuidId>32b930e3-d9da-4ebd-a5b4-fbc81921b772</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='add-to-cart-button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3cb0f9a8-181e-40d2-a61a-0fc2ee0543b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-to-cart-button</value>
      <webElementGuid>75fd39bf-79a5-4ef8-a3d9-0445930a6ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.add-to-cart</value>
      <webElementGuid>e7d077d7-b717-4fd1-8257-20ed33a146f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add to Shopping Cart</value>
      <webElementGuid>fb90bf4b-9209-479e-926d-4cc03683940a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>Select &lt;b>__dims__&lt;/b> from the left&lt;br> to add to Shopping Cart</value>
      <webElementGuid>68f5877a-5696-43f4-bc4b-8a50b793b591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>49da3ddb-af22-4158-b176-903f42a0252b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0b5784b1-2247-4169-8174-9c532c33a48a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add to Cart</value>
      <webElementGuid>10affd11-5afa-4ba6-a312-68faf4a936b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>submit.add-to-cart-announce</value>
      <webElementGuid>b526b3ae-1717-47de-a9e7-dfe7f67864cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formaction</name>
      <type>Main</type>
      <value>/cart/add-to-cart/ref=dp_start-bbf_1_glance</value>
      <webElementGuid>bf513ee7-acb9-4ddb-85f2-cefb6ff7db02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktop_qualifiedBuyBox&quot;)/div[@class=&quot;a-section a-spacing-none a-padding-none&quot;]/div[@id=&quot;addToCart_feature_div&quot;]/div[@class=&quot;a-button-stack&quot;]/span[@id=&quot;atc-declarative&quot;]/span[@id=&quot;submit.add-to-cart&quot;]/span[@class=&quot;a-button-inner&quot;]/input[@id=&quot;add-to-cart-button&quot;]</value>
      <webElementGuid>a24acb84-7f5d-4673-99f9-9324a0d25b0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='add-to-cart-button'])[2]</value>
      <webElementGuid>da45da21-f439-40b7-8a2b-b0569c08b696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//span[@id='submit.add-to-cart']/span/input)[2]</value>
      <webElementGuid>5cf64f2c-de0e-46b8-a9a8-72d8866c01df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[39]/div/span/span/span/input</value>
      <webElementGuid>c1f03845-f48d-457e-b59c-4702201c9bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'add-to-cart-button' and @name = 'submit.add-to-cart' and @title = 'Add to Shopping Cart' and @type = 'submit']</value>
      <webElementGuid>3ab0da58-fb40-4719-be5c-391d13d9702b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
